name: eBiznes Projekt_zaliczeniowy Backend

on:
  push:
    branches: [ "main" ]
    
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/ebiznes_ktor_backend

jobs:
  build-and-deploy:
    environment: Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend_KTOR

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: FixCORS
        run: sed -i 's+localhost:3000+wojciechklasa-frontend.azurewebsites.net+g' src/main/kotlin/com/example/plugins/HTTP.kt

      - name: DisplayHTTP.kt
        run: less src/main/kotlin/com/example/plugins/HTTP.kt

      #- name: FixCookies
      #  run: sed -i '22 i cookie.secure=true \n cookie.extensions["SameSite"] = "None"' src/main/kotlin/com/example/plugins/Sessions.kt
        
      - name: DisplayHTTP.kt
        run: less src/main/kotlin/com/example/plugins/Sessions.kt
        
      - name: Login into DockerHub
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - name: Build the Docker image
        run: docker build --file Dockerfile -t $DOCKER_HUB_IMAGE_NAME -t $DOCKER_HUB_IMAGE_NAME:${{ github.sha }} .
      
      - name: Push the Docker image
        run: docker push $DOCKER_HUB_IMAGE_NAME --all-tags
        
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'WojciechKlasaServerBackend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          images: ${{ env.DOCKER_HUB_IMAGE_NAME }}:${{ github.sha }}
